[tool.poetry]
name = "day-4"
version = "0.1.0"
description = ""
authors = ["Sergei Timokhin <sergei.timokhin@statecraft.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
